### PR TITLE
[static_shock repo]: Delete and ignore pubspec.lock in all packages (resolves #132)

### LINKED ISSUE #132: Add pubspec.lock to .gitignore
Dart frequently updates `pubspec.lock`. When multiple developers are fetching and pushing changes to a shared repo, `pubspec.lock` is a common source of merge conflicts. It also pollutes the PR, making it harder to review.

## Reproduction steps:

1. Run `dart pub get` after any project dependency has changed.
2. Add and commit changes with `git`.
3. Open a PR on the upstream repo.

## Expected result:

The PR should omit any local changes to `pubspec.lock`. The `static_shock` repo should not include `pubspec.lock` files at all.

## Actual result:

The PR includes `pubspec.lock` (potentially more than one, since `static_shock` includes multiple packages).

## Resolving ambiguities

This PR could be resolved by adding `pubspec.lock` to `.gitignore`. In fact, this is the recommendation for libraries in the [Dart documentation](https://dart.dev/guides/libraries/private-files#pubspeclock).

Committing `pubspec.lock` to source control may perhaps be useful  at times for an application where all of the developers need to ensure that they are building exactly the same binary. However, for shared libraries it is better for everyone to create their `pubspec.lock` files locally.

I'm _not_ suggesting we add `pubspec.lock` to the `.gitignore` of generated projects, only to the `static_shock` repo itself.

I _am_ suggesting we specifically add `pubspec.lock` to the `.gitignore` at the top level. Adding it to sub-packages is also fine, but would be unnecessary if it were already included at the top level. The reason for this is that it's easy to forget when adding another package. For example, `packages/static_shock` includes it while the other packages omit it. Apparently that was just an oversight.

### PR DESCRIPTION
**Pull request by suragch**
Delete and ignore `pubspec.lock` in all packages.

This PR does the following two things:

- Deletes all existing `pubspec.lock` files.
- Adds `pubspec.lock` to all `.gitignore` files that didn't previously contain it.

This PR does _not_ affect whether `pubspec.lock` is tracked in generated projects.

### CODE REVIEW

**Comment by matthew-carroll** [comment]
Thanks @suragch. Please be sure to request a review from me on any PR that's ready for review/merge. Otherwise I won't know the PR exists.

**Comment by suragch** [comment]
Hey, @matthew-carroll 
I'm not sure if it's a permissions issue or something that needs to be enabled in settings, but I don't have an option to select a reviewer on this repo. This is what I see:

Screenshot 2024-06-01 at 16 45 24

**Comment by matthew-carroll** [comment]
I just invited you to join the repo. Also, you can "@" me in a comment and that will email me, too.

**Comment by suragch** [comment]
@matthew-carroll Thanks. Got it. I assumed that you got emails for PRs as well, but I'll @ you for PRs in other repos in the future.

**Pull request merged**
