### PR TITLE
Added a 'Finisher' hook to run behaviors after all pages are indexed and rendered (Resolves #36)

### LINKED ISSUE #36: Create pipeline hook that runs after all pages are indexed
An RSS feed needs to process all pages, in their final form. Currently, there's no opportunity to run code after all pages are indexed. Add that for RSS and other related behaviors.

### PR DESCRIPTION
**Pull request by matthew-carroll**
Added a 'Finisher' hook to run behaviors after all pages are indexed and rendered (Resolves #36)

Register a `Finisher` with the pipeline:

```dart
staticShock
  ..pick()
  ..finish(myFinisher)
  ..plugin()
```

### CODE REVIEW

**Comment by csells** [comment]
What can a finisher do? Can it generate new files to be rendered, e.g. one or more RSS or ATOM files?

I don't see any docs in this PR. Shouldn't there be?

**Comment by matthew-carroll** [comment]
> I don't see any docs in this PR

Dart Docs were written for the new behaviors. Those docs are brief, but they exist. What do you think should be added to them?

> What can a finisher do? Can it generate new files to be rendered, e.g. one or more RSS or ATOM files?

It can do anything that can be done with a `StaticShockPipelineContext`, which should include the ability to create new files, including an RSS feed.

**Comment by csells** [comment]
> What do you think should be added to them?

Sorry. API reference docs weren't what I had in mind; currently this is what it says about building a finisher: "An action that runs after all pages are loaded, indexed, and written to their destination." and "Adds the given [Finisher] to the pipeline, which runs after all [Page]s are loaded, indexed, transformed, and rendered. A [Finisher] might be used, for example, to generate an RSS feed, which requires knowledge of all pages in the static site."

Conceptually, that's true, but without some kind of example Finisher implementation, devs don't really have actionable docs. I was looking for how-to docs for the website ala a guide.

> It can do anything that can be done with a `StaticShockPipelineContext`, which should include the ability to create new files, including an RSS feed.

That's useful info, too, which isn't mentioned in the docs I read.

**Comment by csells** [comment]
the other way to go would be to open up a bug about how-to docs, assign it to me and I can write it once I've figured out how to build an RSS generator.

**Comment by matthew-carroll** [comment]
Yeah the website will definitely need a guide. I was hoping we could prove that the API works for you before writing the guide. Do you think you see enough details to attempt the RSS plugin implementation after merging this in? I stubbed an RSS plugin implementation for you.

**Comment by csells** [comment]
I saw that. Thanks.

**Review by csells — APPROVED** [review]

**Pull request merged**
